stages:
  - build
  - deploy
  - cleanup

variables:
  PULUMI_SKIP_UPDATE_CHECK: true
  AWS_REGION: "us-east-1"

image:
  name: registry.cn-hangzhou.aliyuncs.com/goldenimage/pulumi:3.35.3

before_script:
  - cp /etc/gitlab-runner/certs/gitlab.home.local.crt /usr/local/share/ca-certificates/ca.crt
  - update-ca-certificates
  - pulumi login 's3://state?endpoint=minio.home.local:80&disableSSL=true&s3ForcePathStyle=true'
  - pulumi stack select azure-network

build:
  stage: build
  script:
    - pulumi plugin install resource azure-native v2.68.0 --server https://obs.home.local/mirror/pulumi/plugins
    - pulumi plugin install resource random v4.16.7 --server https://obs.home.local/mirror/pulumi/plugins
    - npm config set registry https://registry.npmmirror.com
    - npm install
    - git -c http.sslVerify=false clone https://gitea.home.local/suzhetao/pulumi-ts-module-azure.git
  artifacts:
    paths:
      - node_modules
      - pulumi-ts-module-azure
    expire_in: 6 hours
    when: on_success

deploy:
  stage: deploy
  script:
    - pulumi up -yf
  rules:
    - if: $CI_COMMIT_TITLE == "deploy"
      when: on_success 

cleanup:
  stage: cleanup
  script:
    - pulumi destroy -yf
  rules:
    - if: $CI_COMMIT_TITLE == "destroy"
      when: on_success